### ISSUE TITLE
Colors don't reset properly in Powershell.exe

### ISSUE THREAD

**Issue by floyd-may** [TooTallNate/ansi.js#22]
This code has some interesting behavior on powershell:

    var ansi = require('ansi');

    var ansiLogger = ansi(process.stderr);

    ansiLogger.fg.red();
    ansiLogger.bg.grey();

    ansiLogger.write('colored output\n').reset();

Now, in ConEmu (my terminal of choice on Windows), this works fine:

![image](https://cloud.githubusercontent.com/assets/1608756/8006976/15ed68da-0b5e-11e5-90ab-09dd535c65ae.png)

However, if I use powershell.exe by itself, the colors don't reset properly:
![image](https://cloud.githubusercontent.com/assets/1608756/8007014/4c7f9d00-0b5e-11e5-81f2-784e59442fa2.png)

See how the BG of all the text emitted afterwards is black? I discovered this originally from a [bug logged to `npm`](https://github.com/npm/npm/issues/2381).

**Comment by stereokai** [comment]
@floyd-may Thanks you very much for putting in the work to discover this.

@TooTallNate - can we do something about this?

**Comment by mvas** [comment]
that seems to be powershell issue.
The ansi itself has only one way to try to restore colors after changing them - and that is sending reset ANSI escape code (https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes)
Reading currently used background and foreground is impossible in general case and node.js does not provide API for doing that, so reseting is the only way.
Unfortunately, powershell treats that code as going back to black_and_white palette.

What I've found as a workaround is to update powershell profile and add [Console]::ResetColor(); to the Prompt function:
![image](https://cloud.githubusercontent.com/assets/1790471/10698234/49b72c30-79b0-11e5-9492-ee9fe299d019.png)
That makes powershell to reset colors when printing prompt.

Ping me if you need more details

**Comment by floyd-may** [comment]
@mvas :+1:

**Comment by YotaXP** [comment]
Is the reset escape code really the proper solution?  This happens in cmd as well if you customize the colors, so it is not specific to Powershell.

![](http://i.imgur.com/73BsX2D.png)

**Comment by mvas** [comment]
This is not a solution, that's a workaround. And for the PowerShell only.

By the way, I've updated my nodejs to 4.1.2 (it happened I used 0.12 before) and issue has gone.

**Comment by floyd-may** [comment]
I confirm what @mvas says:

![image](https://cloud.githubusercontent.com/assets/1608756/10799356/6144b156-7d7a-11e5-9b1f-e2a490fea7d9.png)

Looks like this is an issue with running an out-of-date version of nodejs.
