### ISSUE TITLE
New release with license

### ISSUE THREAD

**Issue by vesan** [TooTallNate/ansi.js#25]
It would be great to have a new release with the LICENSE file and the license information in the package.json.

Thanks!

**Comment by swashcap** [comment]
Seconded. We’re using davglass’s [license-checker](https://github.com/davglass/license-checker) in preparation for un upcoming distribution. It’s flagging ansi!

**Comment by TooTallNate** [comment]
Published as v0.3.1. Sorry for the delay!

**Comment by swashcap** [comment]
Awesome, thanks!

**Comment by vesan** [comment]
Thank you very much @TooTallNate!
