### ISSUE TITLE
Is it possible to make this module work with telnet?

### ISSUE THREAD

**Issue by x13machine** [TooTallNate/ansi.js#26]
The telnet client only sees the text and no colors.
http://pastebin.com/R9kyjVjB

**Comment by TooTallNate** [comment]
See https://github.com/TooTallNate/ansi.js/blob/2504fb83ab85c6f788a9e17d7652f542c409300a/lib/ansi.js#L116-L121. You either need to set `socket.isTTY = true`, or pass `{enabled: true}` as an option when instantiation the ansi.js instance. Cheers!

**Comment by TooTallNate** [comment]
P.S. Feel free to submit a pull request to improve the README on that note. I know that comment in the source code is obscure. Also see #3 :frowning:…
